site_name: DingTalk2
site_description: 钉钉机器人的 Python 库

theme: readthedocs

nav:
  - 快速开始:
      - 项目概述: index.md
      - 安装说明: setup.md
      - 快速上手: quick.md
      - 开发日志: history.md

  - 接口说明:
      - 文本消息: api/text.md
      - 图片消息: api/image.md
      - 卡片消息: api/card.md
      - 链接消息: api/link.md
      - MD 消息: api/markdown.md
